name: API CI

on:
  pull_request:
    branches:
      - master
      - 'release/**'
    paths:
      - 'apps/api/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: apps/api/go.mod
          cache-dependency-path: apps/api/go.sum

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -cover ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.55.2
          working-directory: apps/api
