name: Database Migrations CI

on:
  pull_request:
    branches:
      - master
      - 'release/**'
    paths:
      - 'database/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: database/migrations

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: database/migrations/go.mod
          cache-dependency-path: database/migrations/go.sum

      - name: Build
        run: go build -v ./...
